<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.4.0" />
    <PackageReference Include="Serilog.AspNetCore" Version="8.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Hangfire.AspNetCore" Version="1.7.34" />
    <PackageReference Include="Hangfire.SqlServer" Version="1.7.34" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\WebFormula1.Core\WebFormula1.Core.csproj" />
    <ProjectReference Include="..\WebFormula1.Infrastructure\WebFormula1.Infrastructure.csproj" />
  </ItemGroup>

</Project>
